#if !defined PROTO_TYPEDEF_H
#define PROTO_TYPEDEF_H

#define VAR_TYPE_NAVIGATION       (0x00000001)
#define VAR_TYPE_VEHICLE       (0x00000002)
#define VAR_TYPE_OPERATION       (0x00000003)
#define VAR_TYPE_USER_DEFINED      (0x00000004)
#define VAR_TYPE_OPERATION_PARAMETER    (0x00000005)

#if !defined MAXIMUM_ROBOT_NAME
#define MAXIMUM_ROBOT_NAME       (32)
#endif

#if defined PKTID_AUTOMIC_REPORT
#undef PKTID_AUTOMIC_REPORT
#endif
#define PKTID_AUTOMIC_REPORT      (0xBF007C00)
#if defined ATOMIC_PKTID
#undef ATOMIC_PKTID
#endif
#define ATOMIC_PKTID        (0x0000EE00)
#if defined PKTTYPE_ACK
#undef PKTTYPE_ACK
#endif
#define PKTTYPE_ACK         (0x80000000)

//UDP
#define PKTTYPE_DISCOVER_ROBOT      (0x00000100)
#define PKTTYPE_DISCOVER_ROBOT_ACK     (PKTTYPE_DISCOVER_ROBOT | PKTTYPE_ACK)

// 通用协议
#define PKTTYPE_LOGIN_ROBOT       (0x00000101)
#define PKTTYPE_LOGIN_ROBOT_ACK      (PKTTYPE_LOGIN_ROBOT | PKTTYPE_ACK)

#define PKTTYPE_COMMON_WRITE      (0x00000103)
#define PKTTYPE_COMMON_WRITE_ACK     (PKTTYPE_COMMON_WRITE | PKTTYPE_ACK)

#define PKTTYPE_COMMON_READ_BYID     (0x00000104)
#define PKTTYPE_COMMON_READ_BYID_ACK    (PKTTYPE_COMMON_READ_BYID | PKTTYPE_ACK)

#define PKTTYPE_COMMON_WRITE_BYID     (0x00000105)
#define PKTTYPE_COMMON_WRITE_BYID_ACK    (PKTTYPE_COMMON_WRITE_BYID | PKTTYPE_ACK)

#define PKTTYPE_KEEPALIVE_TCP       (0x00000106)
#define PKTTYPE_KEEPALIVE_TCP_ACK   (PKTTYPE_KEEPALIVE_TCP | PKTTYPE_ACK)

#define PKTTYPE_PRE_LOGIN       (0x00000107)  // connect 完成后， 将密钥推送给客户端
#define PKTTYPE_PRE_LOGIN_ACK      (PKTTYPE_PRE_LOGIN | PKTTYPE_ACK)

#define PKTTYPE_COMMON_STATUS_REPORT    (0x00000108)  // 通用状态报告
#define PKTTYPE_COMMON_STATUS_REPORT_ACK   (PKTTYPE_COMMON_STATUS_REPORT | PKTTYPE_ACK )

#define PKTTYPE_COMMON_COMPARE_WRITE     (0x00000109) // 通用带校验写入
#define PKTTYPE_COMMON_COMPARE_WRITE_ACK    (PKTTYPE_COMMON_COMPARE_WRITE | PKTTYPE_ACK)

#define PKTTYPE_INITIACTIVE_COMMON_READ     (0x0000010A) // 订阅主动读
#define PKTTYPE_INITIACTIVE_COMMON_READ_ACK    (PKTTYPE_INITIACTIVE_COMMON_READ | PKTTYPE_ACK)

#define PKTTYPE_INITIACTIVE_COMMON_READ_CANCLE     (0x0000010B) // 取消主动读
#define PKTTYPE_INITIACTIVE_COMMON_READ_CANCLE_ACK    (PKTTYPE_INITIACTIVE_COMMON_READ_CANCLE | PKTTYPE_ACK)

#define PKTTYPE_INITIACTIVE_READ     (0x0000010C) 
#define PKTTYPE_INITIACTIVE_READ_ACK    (PKTTYPE_INITIACTIVE_READ | PKTTYPE_ACK) // 主动读内容反馈

#define PKTTYPE_KEEPALIVE_UDP       (0x0000010D)
#define PKTTYPE_KEEPALIVE_UDP_ACK   (PKTTYPE_KEEPALIVE_UDP | PKTTYPE_ACK)

#define PKTTYPE_LOCALIZATION_CFGREAD        (0x0000010E)
#define PKTTYPE_LOCALIZATION_CFGREAD_ACK       (PKTTYPE_LOCALIZATION_CFGREAD | PKTTYPE_ACK)

#define PKTTYPE_LOCALIZATION_CFGWRITE        (0x0000010F)
#define PKTTYPE_LOCALIZATION_CFGWRITE_ACK       (PKTTYPE_LOCALIZATION_CFGWRITE | PKTTYPE_ACK)

#define PKTTYPE_READ_WHEELS_BY_DRIVEUNIT    (0x00000110)
#define PKTTYPE_READ_WHEELS_BY_DRIVEUNIT_ACK    (PKTTYPE_READ_WHEELS_BY_DRIVEUNIT |PKTTYPE_ACK )

#define PKTTYPE_COMMON_CALIBRATION_BYID     (0x00000111)
#define PKTTYPE_COMMON_CALIBRATION_BYID_ACK     (PKTTYPE_COMMON_CALIBRATION_BYID | PKTTYPE_ACK )

// 导航任务
#define PKTTYPE_ALLOC_NAVIGATION_TASK    (0x00000201)
#define PKTTYPE_ALLOC_NAVIGATION_TASK_ACK   (PKTTYPE_ALLOC_NAVIGATION_TASK | PKTTYPE_ACK)

#define PKTTYPE_CANCEL_NAVIGATION_TASK    (0x00000202)
#define PKTTYPE_CANCEL_NAVIGATION_TASK_ACK   (PKTTYPE_CANCEL_NAVIGATION_TASK | PKTTYPE_ACK)

#define PKTTYPE_PAUSE_NAVIGATION_TASK    (0x00000203)
#define PKTTYPE_PAUSE_NAVIGATION_TASK_ACK   (PKTTYPE_PAUSE_NAVIGATION_TASK | PKTTYPE_ACK)

#define PKTTYPE_RESUME_NAVIGATION_TASK    (0x00000204)
#define PKTTYPE_RESUME_NAVIGATION_TASK_ACK   (PKTTYPE_RESUME_NAVIGATION_TASK | PKTTYPE_ACK)

#define PKTTYPE_QUERY_NAVIGATION_TASK_STATUS  (0x00000205)
#define PKTTYPE_QUERY_NAVIGATION_TASK_STATUS_ACK (PKTTYPE_QUERY_NAVIGATION_TASK_STATUS | PKTTYPE_ACK)

#define PKTTYPE_QUERY_NAVIGATION_TASK_TRAJ   (0x00000206)
#define PKTTYPE_QUERY_NAVIGATION_TASK_TRAJ_ACK  (PKTTYPE_QUERY_NAVIGATION_TASK_TRAJ | PKTTYPE_ACK)

#define PKTTYPE_ADDITIONAL_NAVIGATION_TRAJECTORY (0x00000207)
#define PKTTYPE_ADDITIONAL_NAVIGATION_TRAJECTORY_ACK (PKTTYPE_ADDITIONAL_NAVIGATION_TRAJECTORY | PKTTYPE_ACK) // 附加导航参考轨迹

#define PKTTYPE_QUERY_REPORT_STATUS (0x00000208)
#define PKTTYPE_QUERY_REPORT_STATUS_ACK (PKTTYPE_QUERY_REPORT_STATUS | PKTTYPE_ACK)

#define PKTTYPE_CANIO_MSG (0x00000209)
#define PKTTYPE_CANIO_MSG_ACK (PKTTYPE_CANIO_MSG | PKTTYPE_ACK)

#define PKTTYPE_ALLOC_OPERATION_TASK    (0x0000020A)
#define PKTTYPE_ALLOC_OPERATION_TASK_ACK (PKTTYPE_ALLOC_OPERATION_TASK | PKTTYPE_ACK)

#define PKTTYPE_CANCEL_OPERATION_TASK   (0x0000020B)
#define PKTTYPE_CANCEL_OPERATION_TASK_ACK   (PKTTYPE_CANCEL_OPERATION_TASK | PKTTYPE_ACK)

#define PKTTYPE_PAUSE_OPERATION_TASK    (0x0000020C)
#define PKTTYPE_PAUSE_OPERATION_TASK_ACK    (PKTTYPE_PAUSE_OPERATION_TASK | PKTTYPE_ACK)

#define PKTTYPE_RESUME_OPERATION_TASK   (0x0000020D)
#define PKTTYPE_RESUME_OPERATION_TASK_ACK   (PKTTYPE_RESUME_OPERATION_TASK | PKTTYPE_ACK )

// 定制操作
#define PKTTYPE_QUERY_OPERATION_PARAMETER   (0x00000301)
#define PKTTYPE_QUERY_OPERATION_PARAMETER_ACK  ( PKTTYPE_QUERY_OPERATION_PARAMETER | PKTTYPE_ACK )  // 获取操作参数

#define PKTTYPE_SET_OPERATION_PARAMETER    (0x00000302)
#define PKTTYPE_SET_OPERATION_PARAMETER_ACK   (PKTTYPE_SET_OPERATION_PARAMETER | PKTTYPE_ACK)  // 主动设置操作参数

// 调试信息
#define PKTTYPE_DBG_LOG_REPORT                              (0x00000401) // 下位机日志信息直接传递给在连上端(无需应答)
#define PKTTYPE_DBG_LOG_REPORT_ACK                              (PKTTYPE_DBG_LOG_REPORT | PKTTYPE_ACK)          

#define PKTTYPE_DBG_VARLS                               (0x00000402)  // 要求下位机报告所有的变量， 及其类型
#define PKTTYPE_DBG_VARLS_ACK                           (PKTTYPE_DBG_VARLS | PKTTYPE_ACK)

#define PKTTYPE_DBG_CLEAR_FAULT                         (0x00000403)    /* 手动清除错误 */
#define PKTTYPE_DBG_CLEAR_FAULT_ACK                     (PKTTYPE_DBG_CLEAR_FAULT | PKTTYPE_ACK)

#define PKTTYPE_DBG_GET_MTVER							(0x00000404)    /* get version of current running motion template program */
#define PKTTYPE_DBG_GET_MTVER_ACK						(PKTTYPE_DBG_GET_MTVER | PKTTYPE_ACK)

#define PKTTYPE_DBG_SIGSEGV								(0x00000405)

//picking station 
#define PKTTYPE_PINCKING_STATION_KEEP_ALIVE  (0x00000500)
#define PKTTYPE_PINCKING_STATION_KEEP_ALIVE_ACK   (PKTTYPE_PINCKING_STATION_KEEP_ALIVE|PKTTYPE_ACK)

#define PKTTYPE_PINCKING_STATION_PRE_LOGIN   (0x00000501)
#define PKTTYPE_PINCKING_STATION_PRE_LOGIN_ACK   (PKTTYPE_PRE_LOGIN|PKTTYPE_ACK)
//#define PKTTYPE_PINCKING_STATION_PRE_LOGIN_ACK   (PKTTYPE_PINCKING_STATION_PRE_LOGIN|PKTTYPE_ACK)

#define PKTTYPE_PINCKING_STATION_LOGIN_ROBOT   (0x00000502)
#define PKTTYPE_PINCKING_STATION_LOGIN_ROBOT_ACK   (PKTTYPE_LOGIN_ROBOT|PKTTYPE_ACK)
//#define PKTTYPE_PINCKING_STATION_LOGIN_ROBOT_ACK   (PKTTYPE_PINCKING_STATION_LOGIN_ROBOT|PKTTYPE_ACK)

#define PKTTYPE_PICKING_GUIDE_INFO   (0x00000503)
#define PKTTYPE_PICKING_GUIDE_INFO_ACK   (PKTTYPE_PICKING_GUIDE_INFO|PKTTYPE_ACK)

#define PKTTYPE_REPLEN_GUIDE_INFO   (0x00000504)
#define PKTTYPE_REPLEN_GUIDE_INFO_ACK   (PKTTYPE_REPLEN_GUIDE_INFO|PKTTYPE_ACK)

//调度系统 
#define PKTTYPE_DISPATCH_MONITOR_KEEP_ALIVE  (0x00000600)
#define PKTTYPE_DISPATCH_MONITOR_KEEP_ALIVE_ACK   (PKTTYPE_DISPATCH_MONITOR_KEEP_ALIVE|PKTTYPE_ACK)

#define PKTTYPE_DISPATCH_MONITOR_PRE_LOGIN   (0x00000601)
#define PKTTYPE_DISPATCH_MONITOR_PRE_LOGIN_ACK   (PKTTYPE_DISPATCH_MONITOR_PRE_LOGIN|PKTTYPE_ACK)

#define PKTTYPE_DISPATCH_MONITOR_LOGIN_ROBOT   (0x00000602)
#define PKTTYPE_DISPATCH_MONITOR_LOGIN_ROBOT_ACK   (PKTTYPE_DISPATCH_MONITOR_LOGIN_ROBOT|PKTTYPE_ACK)

#define PKTTYPE_INIT_AGV_SOFTWARE   (0x00000603)
#define PKTTYPE_INIT_AGV_SOFTWARE_ACK   (PKTTYPE_INIT_AGV_SOFTWARE|PKTTYPE_ACK)

#define PKTTYPE_CREATE_AGV_AGENT   (0x00000604)
#define PKTTYPE_CREATE_AGV_AGENT_ACK   (PKTTYPE_CREATE_AGV_AGENT|PKTTYPE_ACK)

#define PKTTYPE_DESTORY_AGV_AGENT   (0x00000605)
#define PKTTYPE_DESTORY_AGV_AGENT_ACK   (PKTTYPE_DESTORY_AGV_AGENT|PKTTYPE_ACK)

#define PKTTYPE_CREATE_AGV_INTERFACE   (0x00000606)
#define PKTTYPE_CREATE_AGV_INTERFACE_ACK   (PKTTYPE_CREATE_AGV_INTERFACE|PKTTYPE_ACK)

#define PKTTYPE_DESTORY_AGV_INTERFACE   (0x00000607)
#define PKTTYPE_DESTORY_AGV_INTERFACE_ACK   (PKTTYPE_DESTORY_AGV_INTERFACE|PKTTYPE_ACK)

#define PKTTYPE_CONNECT_AGV_INTERFACE   (0x00000608)
#define PKTTYPE_CONNECT_AGV_INTERFACE_ACK   (PKTTYPE_CONNECT_AGV_INTERFACE|PKTTYPE_ACK)

#define PKTTYPE_DISCONNECT_AGV_INTERFACE   (0x00000609)
#define PKTTYPE_DISCONNECT_AGV_INTERFACE_ACK   (PKTTYPE_DISCONNECT_AGV_INTERFACE|PKTTYPE_ACK)

#define PKTTYPE_NOTIFY_READY   (0x0000060A)
#define PKTTYPE_NOTIFY_READY_ACK   (PKTTYPE_NOTIFY_READY|PKTTYPE_ACK)

#define PKTTYPE_PUT_PICKING_AGV_IN_DISPATCHER   (0x0000060B)
#define PKTTYPE_PUT_PICKING_AGV_IN_DISPATCHER_ACK   (PKTTYPE_PUT_PICKING_AGV_IN_DISPATCHER|PKTTYPE_ACK)

#define PKTTYPE_REMOVE_PICKING_AGV_FROM_DISPATCHER   (0x0000060C)
#define PKTTYPE_REMOVE_PICKING_AGV_FROM_DISPATCHER_ACK   (PKTTYPE_REMOVE_PICKING_AGV_FROM_DISPATCHER|PKTTYPE_ACK)

#define PKTTYPE_GET_PICKING_AGV_DISPATCHER_CONTEX   (0x0000060D)
#define PKTTYPE_GET_PICKING_AGV_DISPATCHER_CONTEX_ACK   (PKTTYPE_GET_PICKING_AGV_DISPATCHER_CONTEX|PKTTYPE_ACK)

#define PKTTYPE_PUT_CART_AGV_IN_DISPATCHER   (0x0000060E)
#define PKTTYPE_PUT_CART_AGV_IN_DISPATCHER_ACK   (PKTTYPE_PUT_CART_AGV_IN_DISPATCHER|PKTTYPE_ACK)

#define PKTTYPE_REMOVE_CART_AGV_FROM_DISPATCHER   (0x0000060F)
#define PKTTYPE_REMOVE_CART_AGV_FROM_DISPATCHER_ACK   (PKTTYPE_REMOVE_CART_AGV_FROM_DISPATCHER|PKTTYPE_ACK)

#define PKTTYPE_GET_CART_AGV_DISPATCHER_CONTEX   (0x00000610)
#define PKTTYPE_GET_CART_AGV_DISPATCHER_CONTEX_ACK   (PKTTYPE_GET_CART_AGV_DISPATCHER_CONTEX|PKTTYPE_ACK)

#define PKTTYPE_CANCLE_TASK  (0x00000611)
#define PKTTYPE_CANCLE_TASK_ACK   (PKTTYPE_CANCLE_TASK|PKTTYPE_ACK)

#define PKTTYPE_CLEAR_FAULT  (0x00000612)
#define PKTTYPE_CLEAR_FAULT_ACK   (PKTTYPE_CLEAR_FAULT|PKTTYPE_ACK)

#define PKTTYPE_RETRY_OPERATION  (0x00000613)
#define PKTTYPE_RETRY_OPERATION_ACK   (PKTTYPE_RETRY_OPERATION|PKTTYPE_ACK)

#define PKTTYPE_CONTINUE_TASK  (0x00000614)
#define PKTTYPE_CONTINUE_TASK_ACK   (PKTTYPE_CONTINUE_TASK|PKTTYPE_ACK)

#define PKTTYPE_FORCE_RESASRT_VEHICLE  (0x00000615)
#define PKTTYPE_FORCE_RESASRT_VEHICLE_ACK   (PKTTYPE_FORCE_RESASRT_VEHICLE|PKTTYPE_ACK)

#define PKTTYPE_START_ALL  (0x00000616)
#define PKTTYPE_START_ALL_ACK   (PKTTYPE_START_ALL|PKTTYPE_ACK)

#define PKTTYPE_RESASRT_ALL  (0x00000617)
#define PKTTYPE_RESASRT_ALL_ACK   (PKTTYPE_RESASRT_ALL|PKTTYPE_ACK)

#define PKTTYPE_CREATE_ALL  (0x00000618)
#define PKTTYPE_CREATE_ALL_ACK   (PKTTYPE_CREATE_ALL|PKTTYPE_ACK)

#define PKTTYPE_SET_READY_ALL  (0x00000619)
#define PKTTYPE_SET_READY_ALL_ACK   (PKTTYPE_SET_READY_ALL|PKTTYPE_ACK)

#define PKTTYPE_IN_DISPATCH_ALL  (0x0000061A)
#define PKTTYPE_IN_DISPATCH_ALL_ACK   (PKTTYPE_IN_DISPATCH_ALL|PKTTYPE_ACK)

#define PKTTYPE_REMOVE_DISPATCH_ALL  (0x0000061B)
#define PKTTYPE_REMOVE_DISPATCH_ALL_ACK   (PKTTYPE_REMOVE_DISPATCH_ALL|PKTTYPE_ACK)

#define PKTTYPE_DESTORY_DISPATCH  (0x0000061C)
#define PKTTYPE_DESTORY_DISPATCH_ACK   (PKTTYPE_DESTORY_DISPATCH|PKTTYPE_ACK)

#define PKTTYPE_SET_PALLET_MISSING  (0x0000061D)
#define PKTTYPE_SET_PALLET_MISSING_ACK   (PKTTYPE_SET_PALLET_MISSING|PKTTYPE_ACK)

#define PKTTYPE_SET_PALLET_MISSING_BY_AGV  (0x0000061E)
#define PKTTYPE_SET_PALLET_MISSING_BY_AGV_ACK   (PKTTYPE_SET_PALLET_MISSING_BY_AGV|PKTTYPE_ACK)

#define PKTTYPE_RESET_MISSNGING_PALLET  (0x0000061F)
#define PKTTYPE_RESET_MISSNGING_PALLET_ACK   (PKTTYPE_RESET_MISSNGING_PALLET|PKTTYPE_ACK)

#define PKTTYPE_RESET_ALL_MISSNGING_PALLET  (0x00000620)
#define PKTTYPE_RESET_ALL_MISSNGING_PALLET_ACK   (PKTTYPE_RESET_ALL_MISSNGING_PALLET|PKTTYPE_ACK)

#define PKTTYPE_SET_PALLET_LOCATION  (0x00000621)
#define PKTTYPE_SET_PALLET_LOCATION_ACK   (PKTTYPE_SET_PALLET_LOCATION|PKTTYPE_ACK)

#define PKTTYPE_SKIP_NEXT_PICK  (0x00000622)
#define PKTTYPE_SKIP_NEXT_PICK_ACK   (PKTTYPE_SKIP_NEXT_PICK|PKTTYPE_ACK)

#define PKTTYPE_SET_CART_TO_PICKSTATION  (0x00000623)
#define PKTTYPE_SET_CART_TO_PICKSTATION_ACK   (PKTTYPE_SET_CART_TO_PICKSTATION|PKTTYPE_ACK)

#define PKTTYPE_GET_PALLET_TRACE_INFO  (0x00000624)
#define PKTTYPE_GET_PALLET_TRACE_INFO_ACK   (PKTTYPE_GET_PALLET_TRACE_INFO|PKTTYPE_ACK)

#define PKTTYPE_PICKING_AGV_TRACE  (0x00000625)
#define PKTTYPE_PICKING_AGV_TRACE_ACK   (PKTTYPE_PICKING_AGV_TRACE|PKTTYPE_ACK)

#define PKTTYPE_CART_AGV_TRACE  (0x00000626)
#define PKTTYPE_CART_AGV_TRACE_ACK   (PKTTYPE_CART_AGV_TRACE|PKTTYPE_ACK)

#define PKTTYPE_CARTS_SATAISTICS  (0x00000627)
#define PKTTYPE_CARTS_SATAISTICS_ACK   (PKTTYPE_CARTS_SATAISTICS|PKTTYPE_ACK)

#define PKTTYPE_PICKING_AND_CART_POSITION  (0x00000628)
#define PKTTYPE_PICKING_AND_CART_POSITION_ACK   (PKTTYPE_PICKING_AND_CART_POSITION|PKTTYPE_ACK)

#define PKTTYPE_GET_PALLET_BASE_INFO  (0x00000629)
#define PKTTYPE_GET_PALLET_BASE_INFO_ACK   (PKTTYPE_GET_PALLET_BASE_INFO|PKTTYPE_ACK)

#define PKTTYPE_GET_ALLOCATE_AGV  (0x0000062A)
#define PKTTYPE_GET_ALLOCATE_AGV_ACK   (PKTTYPE_GET_ALLOCATE_AGV|PKTTYPE_ACK)

#define PKTTYPE_GET_PICKING_AND_CART_STATUS  (0x0000062B)
#define PKTTYPE_GET_PICKING_AND_CART_STATUS_ACK   (PKTTYPE_GET_PICKING_AND_CART_STATUS|PKTTYPE_ACK)

#define PKTTYPE_CLOSE_AGV_SOFTWARE  (0x0000062C)
#define PKTTYPE_CLOSE_AGV_SOFTWARE_ACK (PKTTYPE_CLOSE_AGV_SOFTWARE | PKTTYPE_ACK)

#define PKTTYPE_CLOSE_ALL (0x0000062D)
#define PKTTYPE_CLOSE_ALL_ACK (PKTTYPE_CLOSE_ALL | PKTTYPE_ACK)

#define PKTTYPE_FREEZE_All  (0x0000062E)
#define PKTTYPE_FREEZE_All_ACK (PKTTYPE_FREEZE_All | PKTTYPE_ACK)

#define PKTTYPE_UNFREEZE_All  (0x0000062F)
#define PKTTYPE_UNFREEZE_All_ACK (PKTTYPE_UNFREEZE_All | PKTTYPE_ACK)

#define PKTTYPE_GET_FREEZE_All  (0x00000630)
#define PKTTYPE_GET_FREEZE_All_ACK (PKTTYPE_GET_FREEZE_All | PKTTYPE_ACK)

#define PKTTYPE_ENABLE_SAFETY  (0x00000631)
#define PKTTYPE_ENABLE_SAFETY_ACK (PKTTYPE_ENABLE_SAFETY | PKTTYPE_ACK)

#define PKTTYPE_DISABLE_SAFETY  (0x00000632)
#define PKTTYPE_DISABLE_SAFETY_ACK (PKTTYPE_DISABLE_SAFETY | PKTTYPE_ACK)

#define PKTTYPE_SET_CART_AGV_LIFT_UP  (0x00000633)
#define PKTTYPE_SET_CART_AGV_LIFT_UP_ACK (PKTTYPE_SET_CART_AGV_LIFT_UP | PKTTYPE_ACK)

#define PKTTYPE_SET_CART_AGV_LIFT_DOWN  (0x00000634)
#define PKTTYPE_SET_CART_AGV_LIFT_DOWN_ACK (PKTTYPE_SET_CART_AGV_LIFT_DOWN | PKTTYPE_ACK)

#define PKTTYPE_GET_FAULT_DETAIL  (0x00000635)
#define PKTTYPE_GET_FAULT_DETAIL_ACK (PKTTYPE_GET_FAULT_DETAIL | PKTTYPE_ACK)

#define PKTTYPE_GET_MISSING_PALLETS  (0x00000636)
#define PKTTYPE_GET_MISSING_PALLETS_ACK (PKTTYPE_GET_MISSING_PALLETS | PKTTYPE_ACK)

#define PKTTYPE_SET_PALLET_TO_STATION  (0x00000637)
#define PKTTYPE_SET_PALLET_TO_STATION_ACK   (PKTTYPE_SET_PALLET_TO_STATION|PKTTYPE_ACK)

#define PKTTYPE_SET_CART_STATUS  (0x00000638)
#define PKTTYPE_SET_CART_STATUS_ACK   (PKTTYPE_SET_CART_STATUS|PKTTYPE_ACK)

#define PKTTYPE_START_CHARGE  (0x00000639)
#define PKTTYPE_START_CHARGE_ACK (PKTTYPE_START_CHARGE | PKTTYPE_ACK)

#define PKTTYPE_END_CHARGE  (0x0000063a)
#define PKTTYPE_END_CHARGE_ACK (PKTTYPE_END_CHARGE | PKTTYPE_ACK)


/***********************************************agv shell协议段**************************************************/
#define PKTTYPE_AGV_SHELL_PRE_LOGIN   (0x00000701)
#define PKTTYPE_AGV_SHELL_PRE_LOGIN_ACK   (PKTTYPE_DISPATCH_MONITOR_PRE_LOGIN|PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_LOGIN_ROBOT   (0x00000702)
#define PKTTYPE_AGV_SHELL_LOGIN_ROBOT_ACK   (PKTTYPE_DISPATCH_MONITOR_LOGIN_ROBOT|PKTTYPE_ACK)

#endif