#ifndef __PROTO_AGV_SHELL_DEF_H__
#define __PROTO_AGV_SHELL_DEF_H__

#define INVALID_PACK_TYPE		((uint32_t)~0)
#define PKTTYPE_UNKNOWN			( INVALID_PACK_TYPE )

#if defined PKTTYPE_AGV_SHELL
#undef PKTTYPE_AGV_SHELL
#endif
#define PKTTYPE_AGV_SHELL         (0x00010000)

#if defined PKTTYPE_ACK
#undef PKTTYPE_ACK
#endif
#define PKTTYPE_ACK         (0x80000000)

#define PKTTYPE_AGV_SHELL_PRE_LOGIN                     (0x00000001 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_PRE_LOGIN_ACK                 (PKTTYPE_AGV_SHELL_PRE_LOGIN | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_LOGIN                         (0x00000002 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_LOGIN_ACK                     (PKTTYPE_AGV_SHELL_LOGIN | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_KEEPALIVE                     (0x00000003 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_KEEPALIVE_ACK                 (PKTTYPE_AGV_SHELL_KEEPALIVE | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_PROCESS_STATUS                (0x00000004 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_PROCESS_STATUS_ACK            (PKTTYPE_AGV_SHELL_PROCESS_STATUS | PKTTYPE_ACK)

// Status CmdList
#define PKTTYPE_AGV_SHELL_GET_PROCESS_LIST              (0x00000005 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_GET_PROCESS_LIST_ACK          (PKTTYPE_AGV_SHELL_GET_PROCESS_LIST | PKTTYPE_ACK)
// UpdateCmdList
#define PKTTYPE_AGV_SHELL_SET_PROCESS_LIST              (0x00000006 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_SET_PROCESS_LIST_ACK          (PKTTYPE_AGV_SHELL_SET_PROCESS_LIST | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_PROCESS_COMMAND               (0x00000007 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_PROCESS_COMMAND_ACK           (PKTTYPE_AGV_SHELL_PROCESS_COMMAND | PKTTYPE_ACK)


// VCU
#define PKTTYPE_AGV_SHELL_FRIMWARE_INFO                 (0x00000101 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_FRIMWARE_INFO_ACK             (PKTTYPE_AGV_SHELL_FRIMWARE_INFO | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_FRIMWARE_UPDATE               (0x00000102 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_FRIMWARE_UPDATE_ACK           (PKTTYPE_AGV_SHELL_FRIMWARE_UPDATE | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_FRIMWARE_DOWNLOAD             (0x00000103 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_FRIMWARE_DOWNLOAD_ACK         (PKTTYPE_AGV_SHELL_FRIMWARE_DOWNLOAD | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_FRIMWARE_RESTART              (0x00000104 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_FRIMWARE_RESTART_ACK          (PKTTYPE_AGV_SHELL_FRIMWARE_RESTART | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_CAN_CUSTOM_UPDATE             (0x00000105 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_CAN_CUSTOM_UPDATE_ACK         (PKTTYPE_AGV_SHELL_CAN_CUSTOM_UPDATE | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_CAN_CUSTOM_INFO               (0x00000106 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_CAN_CUSTOM_INFO_ACK           (PKTTYPE_AGV_SHELL_CAN_CUSTOM_INFO | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_QUERY_VCU_ALIVE_STATUS        (0x00000107 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_QUERY_VCU_ALIVE_STATUS_ACK    (PKTTYPE_AGV_SHELL_QUERY_VCU_ALIVE_STATUS | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_SET_VCU_ALIVE_STATUS          (0x00000108 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_SET_VCU_ALIVE_STATUS_ACK      (PKTTYPE_AGV_SHELL_SET_VCU_ALIVE_STATUS | PKTTYPE_ACK)


// system
#define PKTTYPE_AGV_SHELL_HOSTNAME                      (0x00000201 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_HOSTNAME_ACK                  (PKTTYPE_AGV_SHELL_HOSTNAME | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_UPDATE_NTP                    (0x00000202 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_UPDATE_NTP_ACK                (PKTTYPE_AGV_SHELL_UPDATE_NTP | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_RUN_SCRIPT                    (0x00000203 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_RUN_SCRIPT_ACK                (PKTTYPE_AGV_SHELL_RUN_SCRIPT | PKTTYPE_ACK)
// LocalInfo
#define PKTTYPE_AGV_SHELL_GET_IP_MAC                    (0x00000204 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_GET_IP_MAC_ACK                (PKTTYPE_AGV_SHELL_GET_IP_MAC | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_GET_LOG_TYPE                  (0x00000205 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_GET_LOG_TYPE_ACK              (PKTTYPE_AGV_SHELL_GET_LOG_TYPE | PKTTYPE_ACK)
// TimeTypeConditon
#define PKTTYPE_AGV_SHELL_GET_LOG_FILE_NAME             (0x00000206 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_GET_LOG_FILE_NAME_ACK         (PKTTYPE_AGV_SHELL_GET_LOG_FILE_NAME | PKTTYPE_ACK)
// Logs_Cancel
#define PKTTYPE_AGV_SHELL_CANCEL_GET_LOG                (0x00000207 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_CANCEL_GET_LOG_ACK            (PKTTYPE_AGV_SHELL_CANCEL_GET_LOG | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_FILE_MUTEX_STATUS             (0x00000208 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_FILE_MUTEX_STATUS_ACK         (PKTTYPE_AGV_SHELL_FILE_MUTEX_STATUS | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_MODIFY_FILE_MUTEX             (0x00000209 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_MODIFY_FILE_MUTEX_ACK         (PKTTYPE_AGV_SHELL_MODIFY_FILE_MUTEX | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_SOFT_VERSION_INFO             (0x0000020A | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_SOFT_VERSION_INFO_ACK         (PKTTYPE_AGV_SHELL_SOFT_VERSION_INFO | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_CONFIGFILE_VERSION            (0x0000020B | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_CONFIGFILE_VERSION_ACK        (PKTTYPE_AGV_SHELL_CONFIGFILE_VERSION | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_UPGRADE                       (0x0000020C | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_UPGRADE_ACK                   (PKTTYPE_AGV_SHELL_UPGRADE | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_BACKUP_FILES                  (0x0000020D | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_BACKUP_FILES_ACK              (PKTTYPE_AGV_SHELL_BACKUP_FILES | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_BACKUP_DEMARCATE              (0x0000020E | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_BACKUP_DEMARCATE_ACK          (PKTTYPE_AGV_SHELL_BACKUP_DEMARCATE | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_GET_FIXED_SYSINFO              (0x0000020F | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_GET_FIXED_SYSINFO_ACK          (PKTTYPE_AGV_SHELL_GET_FIXED_SYSINFO | PKTTYPE_ACK)


// transform file
#define PKTTYPE_AGV_SHELL_GET_CATALOG_INFO		        (0x00000301 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_GET_CATALOG_INFO_ACK		    (PKTTYPE_AGV_SHELL_GET_CATALOG_INFO | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_PUSH_FILE_HEAD		        (0x00000302 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_PUSH_FILE_HEAD_ACK	        (PKTTYPE_AGV_SHELL_PUSH_FILE_HEAD | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_PUSH_FILE_BLOCK		        (0x00000303 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_PUSH_FILE_BLOCK_ACK	        (PKTTYPE_AGV_SHELL_PUSH_FILE_BLOCK | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_READ_FILE_HEAD		        (0x00000304 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_READ_FILE_HEAD_ACK	        (PKTTYPE_AGV_SHELL_READ_FILE_HEAD | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_READ_FILE_BLOCK		        (0x00000305 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_READ_FILE_BLOCK_ACK	        (PKTTYPE_AGV_SHELL_READ_FILE_BLOCK | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_FILE_NXET_BLOCK		        (0x00000306 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_FILE_NXET_BLOCK_ACK	        (PKTTYPE_AGV_SHELL_FILE_NXET_BLOCK | PKTTYPE_ACK)

//更新文件状态（完成，发生错误等状态）
#define PKTTYPE_AGV_SHELL_RW_FILE_STATUS				(0x00000307 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_RW_FILE_STATUS_ACK			(PKTTYPE_AGV_SHELL_RW_FILE_STATUS | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_DELETE_FILE					(0x00000308 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_DELETE_FILE_ACK				(PKTTYPE_AGV_SHELL_DELETE_FILE | PKTTYPE_ACK)

//传输状态
#define PKTTYPE_AGV_SHELL_TRANSMIT_STATUS				(0x00000309 | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_TRANSMIT_STATUS_ACK			(PKTTYPE_AGV_SHELL_TRANSMIT_STATUS | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_GET_CURRENT_CATALOG	        (0x0000030A | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_GET_CURRENT_CATALOG_ACK       (PKTTYPE_AGV_SHELL_GET_CURRENT_CATALOG | PKTTYPE_ACK)

//长连接操作
#define PKTTYPE_AGV_SHELL_READ_FILE_LONG_LINK	        (0x0000030B | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_READ_FILE_LONG_LINK_ACK	    (PKTTYPE_AGV_SHELL_READ_FILE_LONG_LINK | PKTTYPE_ACK)

#define PKTTYPE_AGV_SHELL_READ_FILE_BLOCK_LONG          (0x0000030C | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_READ_FILE_BLOCK_LONG_ACK	    (PKTTYPE_AGV_SHELL_READ_FILE_BLOCK_LONG | PKTTYPE_ACK)

//长连接更新文件状态（完成，发生错误等状态）
#define PKTTYPE_AGV_SHELL_RW_FILE_LONG_LNK_STATUS		(0x0000030D | PKTTYPE_AGV_SHELL)
#define PKTTYPE_AGV_SHELL_RW_FILE_LONG_LNK_STATUS_ACK	(PKTTYPE_AGV_SHELL_RW_FILE_LONG_LNK_STATUS | PKTTYPE_ACK)


enum AgvShellCmd {
    None = -1,
    Start = 0,
    Stop,
    ReStart,
    ReBoot,
    ShutDown,
    Max_AGVCMD_NUM,
};

enum AgvClientIdentify {
	AgvClientType_Unknow = 0x100,
	AgvClientType_CMP = (AgvClientType_Unknow << 1), //配置管理平台
};

enum AgvShellKeepaliveStatus {
	AgvShellKeepalive_Unknow = -1,
	AgvShellKeepalive_Start = 0,
	AgvShellKeepalive_Suspend,
};

enum AgvShellKeepaliveReply {
	AgvShellKeepalive_Successful = 0,
	AgvShellKeepalive_Failure,
};

#endif //__PROTO_AGV_SHELL_DEF_H__
